import type { Product } from "../models/product";

/** Catálogo semilla para demostración académica */
export const MENU_SEED: Product[] = [
  {
    id: "combo-campero",
    name: "Combo Campero",
    description: "2 piezas de pollo, papas medianas, biscuit y refresco personal.",
    price: 8.99,
    available: true,
    category: "combos",
  },
  {
    id: "combo-familiar",
    name: "Combo Familiar",
    description: "8 piezas de pollo, 2 papas grandes, 4 biscuits y 2 refrescos.",
    price: 28.5,
    available: true,
    category: "combos",
  },
  {
    id: "piezas-3",
    name: "3 piezas de pollo",
    description: "Tres piezas a elección (muslo, pierna o pechuga).",
    price: 6.25,
    available: true,
    category: "piezas",
  },
  {
    id: "piezas-8",
    name: "8 piezas de pollo",
    description: "Balde con ocho piezas mixtas.",
    price: 14.99,
    available: true,
    category: "piezas",
  },
  {
    id: "papas-mediana",
    name: "Papas fritas medianas",
    description: "Porción mediana de papas crujientes.",
    price: 2.5,
    available: true,
    category: "acompañamientos",
  },
  {
    id: "papas-grande",
    name: "Papas fritas grandes",
    description: "Porción grande ideal para compartir.",
    price: 3.75,
    available: true,
    category: "acompañamientos",
  },
  {
    id: "biscuit-4",
    name: "4 biscuits",
    description: "Cuatro biscuits calientes con miel opcional.",
    price: 3.2,
    available: true,
    category: "biscuits",
  },
  {
    id: "refresco-personal",
    name: "Refresco personal",
    description: "Bebida gaseosa 355 ml (sabor según disponibilidad).",
    price: 1.75,
    available: true,
    category: "refrescos",
  },
  {
    id: "refresco-litro",
    name: "Refresco 1 L",
    description: "Botella familiar 1 litro.",
    price: 3.5,
    available: true,
    category: "refrescos",
  },
  {
    id: "combo-agotado-demo",
    name: "Combo limitado (demo no disponible)",
    description: "Producto de ejemplo con available=false para pruebas de validación.",
    price: 12.0,
    available: false,
    category: "combos",
  },
];
